let challenge = '30 Days Of JavaScript';
console.log(challenge);
console.group(challenge.length);
challenge.toUpperCase();
challenge.toLowerCase();
challenge.substr(1, 21);
console.log(challenge.slice(2, 21));
console.log(challenge.includes('Script'));
challenge.split();
challenge.split(' ');
let redes = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(redes.split(','));
console.log(redes);
challenge.replace('JavaScript', 'Python');
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt('J'));
console.log(challenge.indexOf('a'));
console.log(challenge.lastIndexOf('a'));
let phrase = 'You cannot end a sentence with because because because is a conjunction';
console.log(phrase.indexOf('because'));
console.log(phrase.lastIndexOf('because'));
console.log(phrase.search('because'));
console.log(challenge.trim(' '));
console.log(challenge.startsWith('3'));
console.log(challenge.endsWith('t'));
console.log(challenge.match('a'));
let a = '30 Days Of';
console.log(a.concat(' JavaScript'));
console.log(challenge.repeat(2));